Run installer osbws jar

diff --git a/tasks/install-oswbs.yml b/tasks/install-oswbs.yml
--- a/tasks/install-oswbs.yml
+++ b/tasks/install-oswbs.yml
@@ -1,8 +1,21 @@
 ---
 
-- name: (main/install-oswbs) Copy argfile file template
+- name: (main/install-osbws) Copy argfile file template
   template:
     src: "{{ role_path }}/templates/osbws-argfile.j2"
     dest: "{{ oracle_osbws_installer_directory }}/osbws-argfile"
     owner: "{{ service_user_name }}"
     group: "{{ service_user_group }}"
+
+- name: (main/install-osbws) Install osbws
+  shell: |
+    . ${HOME}/.bash_profile
+    java -verbose -jar "{{ oracle_osbws_installer_directory }}/osbws_install.jar" -ARGFILE "{{ oracle_osbws_installer_directory }}/osbws-argfile" > /dev/null
+    if [ $? -ne 0 ]
+    then
+      echo "Error installing osbws"
+      exit 2
+    fi
+  become_user: "{{ service_user_name }}"
+  register: install
+  failed_when: install.rc !=0
